### PR TITLE
Update to Aspire Preview 7

### PR DESCRIPTION
**Pull request by adityamandaleeka**

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
@adityamandaleeka with P7 out should we merge this?

**Comment by adityamandaleeka** [comment]
We've been merging the ones from dependabot instead (it should open one soon). This is just for early testing.

**Comment by danmoseley** [comment]
Note dependabot is flaky at the moment, so if we want something it can be worth kicking it to have another go. I just did.

**Comment by jamesmontemagno** [comment]
I think all we need to do to this PR is just remove the nuget config changes... we should do that and merge this IMHO

**Comment by danmoseley** [comment]
OK, let's try that.

**Comment by adityamandaleeka** [comment]
I can't sign off on my own PR 😆.

**Review by jamesmontemagno — APPROVED** [review]

**Pull request merged**
