### PR TITLE
Fix NavigationManager in LogIn.razor (#175)

### PR DESCRIPTION
**Pull request by mkhalesi**
for this issue #175

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
I think also: https://github.com/dotnet/eShop/issues/223 ?

**Comment by jamesmontemagno** [comment]
@SrushtiPasari94  to validate

**Comment by mkhalesi** [comment]
> I think also: #223 ?

yes

**Review by SrushtiPasari94 — APPROVED** [review]

**Comment by SrushtiPasari94** [comment]
Approved. This change fixed the login issue.

**Review by jamesmontemagno — APPROVED** [review]

**Pull request merged**
