### PR TITLE
Updates of the MAUI application to .NET 8.0.7 

### PR DESCRIPTION
**Pull request by michaelstonis**
Updates references of the client application to the latest version

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
@michaelstonis  can you sync up brand and then i will fire off the checks

**Comment by michaelstonis** [comment]
@jamesmontemagno anything needed for this PR?

**Comment by jamesmontemagno** [comment]
@michaelstonis merged in

**Comment by jamesmontemagno** [comment]
@michaelstonis  looks like some build issues, can you validate on your end?

**Comment by jamesmontemagno** [comment]
Got it working :)

**Review by jamesmontemagno — APPROVED** [review]

**Pull request merged**
