### PR TITLE
Updated API URL and added versioning

### PR DESCRIPTION
**Pull request by michaelstonis**
The base URL for the API has been updated to a more simplified format. Additionally, versioning parameters have been added to all API calls to ensure compatibility with future updates. This includes changes in methods related to catalog items, brands, types and picture URI generation.

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@jamesmontemagno @Eilon Can you please review these mobile app changes?

**Comment by jamesmontemagno** [comment]
@captainsafia can you take a look at the api changes for verisoning

**Comment by jamesmontemagno** [comment]
LGTM

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
Does this fix up the hybrid app endpoints too @michaelstonis

**Comment by michaelstonis** [comment]
@jamesmontemagno I did not update the endpoints in the hybrid app, but I can take a pass on those too, if you would want.

**Comment by jamesmontemagno** [comment]
@michaelstonis yes please. it should only be like 1 or 2 urls in that app.

**Review by captainsafia — APPROVED** [review]
Versioning-related changes look sensible.

**Pull request merged**
