### PR TITLE
Update developer Android emulator experience for seamless integration with Aspire project, fixes #380

### LINKED ISSUE #380: Unable to login to app when using Duende Identity Server
I get this error when logging in with the MAUI App.

I have all the projects running and I can log into the app using the Website.

System.InvalidOperationException
  Message=Error loading discovery document: Error connecting to https://localhost:5243/.well-known/openid-configuration. Connection failure.

### PR DESCRIPTION
**Pull request by normandev92**
Fixes #380

I followed steps from these pages

- https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/local-web-services?view=net-maui-8.0
- https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?view=net-maui-8.0
- https://stackoverflow.com/questions/67156558/webauthenticator-you-must-subclass-the-webauthenticatorcallbackactivity-and-c

It runs without error now in the MAUI App in the android emulator

eShop_Maui_Andorid

### CODE REVIEW

**Comment by normandev92** [comment]
@dotnet-policy-service agree

**Comment by jamesmontemagno** [comment]
@michaelstonis  to review here please

**Comment by michaelstonis** [comment]
@jamesmontemagno @normandev92 I like the changes here, but I wanted to break them out a bit to separate the functionality and incorporate it a little better with the overall app design.

I have kicked up two PRs that bring in the overall idea behind this PR.

https://github.com/dotnet/eShop/pull/399
https://github.com/dotnet/eShop/pull/401

**Comment by jamesmontemagno** [comment]
Got final tweaks here: https://github.com/dotnet/eShop/pull/402 will close this out. 

Thank you so much for this initial commit that led the way here, can you checkout all the updates on your side.

**Pull request closed without merging**
