### PR TITLE
Update to .NET 9

### PR DESCRIPTION
**Pull request by captainsafia**
Upgrade eShop to .NET 9.

Validated that checkout flow works E2E.

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]
Update readme? It mentions 8.0 sdk

**Comment by nifragos** [comment]
Hello ! is the branch realease/9.0 running ok on your machines? 
In my windows laptop, although it builds successfully, when i try to run it i get :   
   Distributed application started. Press Ctrl+C to shut down.
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      failed to start Executable        {"Executable": {"name":"identity-api-mgs9fb8"}, "Reconciliation": 14, "error": "run session could not be started: failed to connect to IDE run session notification endpoint: unexpected EOF"}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      failed to start Executable        {"Executable": {"name":"basket-api-am7561o"}, "Reconciliation": 15, "error": "run session could not be started: failed to connect to IDE run session notification endpoint: unexpected EOF"}
....

for all the projects

**Comment by captainsafia** [comment]
@nifragos What version of Aspire is installed on your machine?

**Comment by nifragos** [comment]
My Workload is : 
 Workload version: 9.0.100-manifests.f4f7fc79
 [aspire]
   Installation Source: SDK 9.0.100-preview.3, VS 17.10.34902.84
   Manifest Version:    9.0.0-preview.3.24210.17/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.aspire\9.0.0-preview.3.24210.17\WorkloadManifest.json
   Install Type:              Msi

**Comment by captainsafia** [comment]
@nifragos It looks like you're on 9.0.0-preview.3 of Aspire? If so, I'd recommend using [the same version as the repo](https://github.com/dotnet/eShop/blob/release/9.0/Directory.Packages.props#L8).

**Comment by nifragos** [comment]
So what i did was a complete reinstall for .net 8 sdk and everything worked as expected.
The problem was that i did not have the aspire workload on .net 8 . When i upgraded to .net 9 , the workload for aspire was .net 9.
So you should check your aspire folder C:\Program Files\dotnet\sdk-manifests , and verify that also on the .net 8 folder there the aspire workload. Thank you for your help!

**Pull request merged**
